image: 
 name: docker/compose:1.24.0-rc1
 entrypoint: ["/bin/sh", "-c"]
services:
- docker:dind
variables:
 GIT_SUBMODULE_STRATEGY: recursive
 

build:
  script:
  - apt-get install sudo -y
  - sudo docker-compose build
