image: tmaier/docker-compose:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

services:
- docker:dind

build:
  before_script:
  - apk add --no-cache python py2-pip
  - pip install --no-cache-dir docker-compose
  - docker-compose -v
  script:
  - export CI_APPLICATION_REPOSITORY="$CI_REGISTRY_IMAGE"
  - export CI_APPLICATION_TAG="git-$CI_COMMIT_SHA"

  - docker-compose build

  # If you want to push to Docker Hub, set
  # CI_REGISTRY to "docker.io",
  # CI_REGISTRY_IMAGE to "username/repository",
  # CI_REGISTRY_USER, and CI_REGISTRY_PASSWORD
  # via Settings > CI/CD > Variables.
  #
  # You can also set CI_DOCKERHUB_USER, CI_DOCKERHUB_PASSWORD
  # as group variables and only set CI_REGISTRY_IMAGE to "username/repository"
  # on the project.

  - export CI_REGISTRY=docker.io
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  
  - if test "$CI_COMMIT_REF_SLUG" = "master"; then docker push "eaas/eaas-appserver:latest"; fi
  - docker tag eaas/eaas-appserver "eaas/eaas-appserver:$CI_APPLICATION_TAG" 
  - docker push "eaas/eaas-appserver:$CI_APPLICATION_TAG"

  - if test "$CI_COMMIT_REF_SLUG" = "master"; then docker push "eaas/eaas-appserver:latest"; fi
  - docker tag eaas/eaas-proxy "eaas/eaas-proxy:$CI_APPLICATION_TAG"
  - docker push "eaas/eaas-proxy:$CI_APPLICATION_TAG"
  
  

  #- docker export $(docker create build) | gzip > ../container.tar.gz
  #artifacts:
  #  paths:
  #  - container.tar.gz
