image: 
 name: docker
 entrypoint: ["/bin/sh", "-c"]
services:
- docker:dind
variables:
 GIT_SUBMODULE_STRATEGY: recursive
 

build:
  script:
  - apt-get install sudo curl -y
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose build
