image: 
 name: docker/compose:1.24.0-rc1
 entrypoint: ["/bin/sh", "-c"]
services:
- docker:dind
variables:
 GIT_SUBMODULE_STRATEGY: recursive
 DOCKER_HOST: "tcp://docker:2375"
build:
  script:
  - docker-compose build
  - echo $DOCKER_PASS | docker login -u$DOCKER_LOGIN --password-stdin $DOCKER_HOST
  - docker push eaas/citar