image: 
 name: docker/compose:1.24.0-rc1
 entrypoint: ["/bin/sh", "-c"]
services:
- docker:dind
variables:
 GIT_SUBMODULE_STRATEGY: recursive
 DOCKER_HOST: "tcp://docker:2375"
build:
  script:
  - docker-compose build
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "docker.io"
  - docker push "eaas/citar"
  
trigger:
  stage: deploy
  trigger: openslx/emucomp-image-builder