version: '3.2'
services:
  picotcp:
    image: eaas/picotcp
    build: common/eaas-picotcp
  disktype:
    image: eaas/disktype
    build: common/eaas-disktype
  emucon-tools:
    image: eaas/emucon-tools
    build: common/eaas-emucon-tools
  criu:
    image: eaas/criu
    build: common/eaas-criu
  netfilter:
    image: eaas/netfilter
    build: common/netfilter
  vde:
    image: eaas/vde
    build: common/vde-slirp
  base:
    image: eaas/eaas-base
    build: eaas-base
    tty: true
    depends_on:
      - picotcp
      - disktype
      - emucon-tools
      - criu
      - netfilter
      - vde
  eaas-appserver:
    image: eaas/eaas-appserver
    build: eaas-appserver
    depends_on:
      - base
  citar:
    image: eaas/citar
    build: citar-container
    depends_on:
      - base

