version: '3.2'
services:
  custom-packages:
    image: eaas/custom-packages
    build: common/custom-packages
  disktype:
    image: eaas/disktype
    build: common/eaas-disktype
  emucon-tools:
    image: eaas/emucon-tools
    build: common/eaas-emucon-tools
  criu:
    image: eaas/criu
    build: common/eaas-criu
  fake-clock:
    image: eaas/fake-clock
    build: common/fake-clock
  test-sock-diag:
    image: eaas/test-sock-diag
    build: common/test-sock-diag
  netfilter:
    image: eaas/netfilter
    build: common/netfilter
  vde:
    image: eaas/vde
    build: common/vde-slirp
  base:
    image: eaas/eaas-base
    build: eaas-base
    tty: true
    depends_on:
      - custom-packages
      - disktype
      - emucon-tools
      - criu
      - fake-clock
      - netfilter
      - vde
  eaas-appserver:
    image: eaas/eaas-appserver
    build: eaas-appserver
    depends_on:
      - base
  eaas-proxy:
    image: eaas/eaas-proxy
    build: proxy-container
  citar:
    image: eaas/citar
    build: citar-container
    depends_on:
      - base
