#!/bin/sh

sv start eaas || exit 1
sv start syslog-ng || exit 1
echo "starting deployment. this may take a while..."
echo -n "" > /home/bwfla/bw-fla-server/bin/jboss-cli-logging.properties
/home/bwfla/bw-fla-server/bin/jboss-cli.sh --connect --command="deploy --force /eaas/deployments/eaas-server.ear" && logger "Successfully deployed \"eaas-server.ear\"."

sv stop deployment 2>&1 > /dev/null
