#!/bin/sh

echo -n "" > /home/bwfla/bw-fla-server/bin/jboss-cli-logging.properties
mongo eaas  --eval 'db.classificationCache.createIndex( { "classificationResult.objectId": 1 }, { unique: true } )'
mongo eaas  --eval 'db.emilEnv.createIndex( { "emilEnvironment.envId": 1 }, { unique: true, sparse: true})'
mongo eaas  --eval 'db.emilEnv.createIndex( { "emilObjectEnvironment.envId": 1 }, { unique: true, sparse: true})'
mongo eaas  --eval 'db.emilEnv.createIndex( { "emilSessionEnvironment.envId": 1 }, { unique: true, sparse: true})'
/home/bwfla/bw-fla-server/bin/jboss-cli.sh --connect --command="quit"
