#!/bin/sh

# ensure deps are running!
sv -w 120 up mongodb || exit 1
sv -w 120 up wildfly || exit 1

logger 'Preparing mongo-db...'
# TODO: move index creation to Java code, if possible!
mongo eaas  --eval 'db.classificationCache.createIndex( { "classificationResult.objectId": 1 }, { unique: true } )'
# TODO: all following databases are legacy and should be removed!
mongo eaas  --eval 'db.emilEnv.createIndex( { "emilEnvironment.envId": 1 }, { unique: true, sparse: true})'
mongo eaas  --eval 'db.emilEnv.createIndex( { "emilObjectEnvironment.envId": 1 }, { unique: true, sparse: true})'
mongo eaas  --eval 'db.emilEnv.createIndex( { "emilSessionEnvironment.envId": 1 }, { unique: true, sparse: true})'
mongo eaas  --eval 'db.emilEnv.createIndex( { "envId": 1 }, { unique: true, sparse: true})'
mongo eaas  --eval 'db.metadata.createIndex( { "id": 1 }, { unique: true, sparse: true})'

logger 'Deploying eaas-server...'
echo -n "" > /home/bwfla/bw-fla-server/bin/jboss-cli-logging.properties
exec /home/bwfla/bw-fla-server/bin/jboss-cli.sh \
	--connect \
	--command="deploy --force /eaas/deployments/eaas-server.ear"
