#!/bin/sh

if [ -z "${MINIO_ADMIN_KEY}" ]; then
	logger 'Skipping minio setup!'
	exit 0
fi

set -u

logger 'waiting for minio to start'
while ! httping -qc1 http://minio:9000 ; do sleep 1 ; done

logger 'Setting up minio...'
/libexec/mc alias set minio http://minio:9000 "${MINIO_ADMIN_KEY}" "${MINIO_ADMIN_SECRET}"
/libexec/mc admin user add minio "${MINIO_USER_KEY}" "${MINIO_USER_SECRET}"

logger 'Creating local buckets...'
/libexec/mc mb --ignore-existing \
	minio/object-archive \
	minio/image-archive \
	minio/user-data

/libexec/mc admin policy set minio readwrite user="${MINIO_USER_KEY}"
/libexec/mc policy set-json "${MINIO_ARCHIVE_POLICY_FILE}" minio/image-archive
