#!/bin/bash
set -eu
# needed to stay comaptible with old xmount / qemu-img
/usr/bin/_qemu-img "$@"

if [ "$1" == "create" ] || [ "$1" == "rebase" ]; then
# test if last argument was a file
    if [ -f "${@: -1}" ]; then
        truncate --size="$((($(stat --format=%s "${@: -1}") + 511) / 512 * 512))" "${@: -1}"
    elif [ -f "${@: -2:1}" ]; then
        truncate --size="$((($(stat --format=%s "${@: -2:1}") + 511) / 512 * 512))" "${@: -2:1}"
    else
        echo "unexpected error: file not found"
        exit 1
    fi
fi