#!/bin/bash

if ! test -f "/etc/nghttpx/server.crt"; then
  openssl req -x509 -subj "/" -newkey rsa:4096 -days 10000 -nodes \
    -keyout "/etc/nghttpx/server.key" \
    -out "/etc/nghttpx/server.crt" \
    -reqexts SAN \
    -extensions SAN \
    -config <(cat /etc/ssl/openssl.cnf; \
    printf "\n[SAN]\nsubjectAltName=DNS:localhost")
fi

exec /usr/sbin/nghttpx
