#!/bin/sh

user_crt='/eaas/certificates/server.crt'
user_key='/eaas/certificates/server.key'

dstdir='/etc/nghttpx'
server_crt="${dstdir}/server.crt"
server_key="${dstdir}/server.key"

mkdir -p "${dstdir}"

if test -f "${user_crt}"; then
  printf '\nsubcert=%s:%s\n' "${user_key}" "${user_crt}" >> "${dstdir}/nghttpx.conf"
fi

# HACK: Do not create a new fake certificate if one already exists
# as update-ca-certificates will not update Java's CA certificate store otherwise.
if ! test -e "${server_crt}"; then
openssl req -x509 \
  -newkey rsa:4096 -days 10000 -nodes \
  -keyout "${server_key}" -out "${server_crt}" \
  -config - << EOF
prompt=no
distinguished_name=dn
x509_extensions=ext
[dn]
commonName=localhost
[ext]
subjectAltName=DNS:localhost,DNS:eaas
basicConstraints=critical,CA:false
EOF
fi

ls -l "${server_crt}"
openssl x509 -in "${server_crt}" -text
ln -s /etc/nghttpx/server.crt /usr/local/share/ca-certificates/localhost-eaas.crt || true
update-ca-certificates

exec /usr/sbin/nghttpx --workers="$(nproc)"
