#!/bin/sh

set -eu

. "$EAAS_CONFIG_PATH"/dns-env

DOMAIN="$1"

BASEDOMAIN="${DOMAIN#*.}"
CERTDOMAIN="*.$BASEDOMAIN"

ACMESHDIR="/home/bwfla/server-data/acme.sh/"
TEST=""

export LE_CONFIG_HOME="$ACMESHDIR"

# Note: `--days 30` will renew the certificate every 30 days.
# As Let's Encrypt certificates are valid for 90 days,
# this script injects a certificate that is still valid for
# 60 days in the worst case.

# Uncomment if you want Let's Encrypt to generate test certificates.
# TEST="--test"

ret="0"
/usr/local/acme.sh/acme.sh $TEST --dns "$ACMESH_DNS_API" --days 30 --issue -d "$CERTDOMAIN" >&2 || ret="$?"

if ! test "$ret" -eq "0" -o "$ret" -eq "2"; then
  exit "$ret"
fi

CERTFILE="$ACMESHDIR/$CERTDOMAIN/fullchain.cer"
KEYFILE="$ACMESHDIR/$CERTDOMAIN/$CERTDOMAIN.key"

cat << EOF
#cloud-config
write_files:
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /eaas/certificates/server.key
  content: $(base64 --wrap=0 "$KEYFILE")
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /eaas/certificates/server.crt
  content: $(base64 --wrap=0 "$CERTFILE")
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /eaas/certificates/domain
  content: $(printf "%s\n" "$DOMAIN" | base64 --wrap=0)
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /eaas/certificates/certdomain
  content: $(printf "%s\n" "$CERTDOMAIN" | base64 --wrap=0)
#password: eaas
#chpasswd: {expire: false}
EOF
