#!/bin/sh

set -eu

. "$EAAS_CONFIG_PATH"/dns-env

DOMAIN="$1"

BASEDOMAIN="${DOMAIN#*.}"
CERTDOMAIN="*.$BASEDOMAIN"

ACMESHDIR="/home/bwfla/server-data/acme.sh/"
CERTFILE="$ACMESHDIR/$CERTDOMAIN/fullchain.cer"
KEYFILE="$ACMESHDIR/$CERTDOMAIN/$CERTDOMAIN.key"

cat << EOF
#cloud-config
write_files:
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /eaas/certificates/server.key
  content: $(base64 --wrap=0 "$KEYFILE")
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /eaas/certificates/server.crt
  content: $(base64 --wrap=0 "$CERTFILE")
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /eaas/certificates/domain
  content: $(printf "%s\n" "$DOMAIN" | base64 --wrap=0)
- encoding: b64
  owner: root:root
  permissions: "0644"
  path: /eaas/certificates/certdomain
  content: $(printf "%s\n" "$CERTDOMAIN" | base64 --wrap=0)
- path: ${EAAS_CONFIG_PATH}/eaas-config.d/99-imagearchive-domain.yaml
  owner: bwfla:bwfla
  content: |
    ws.imagearchive: https://${DOMAIN}
#password: eaas
#chpasswd: {expire: false}
EOF
