#!/bin/sh

. /home/bwfla/.bwFLA/dns-env || exit

set -eu

acmeshdir='/home/bwfla/server-data/acme.sh/'

export DEPLOY_NGHTTPX_RELOAD="/libexec/update-nghttpx"
export LE_CONFIG_HOME="${acmeshdir}"

__acmesh() {
	# convert return-code 2 to 0, else return original value
	local rc='0'
	/usr/local/acme.sh/acme.sh "$@" || rc="$?"
	test "${rc}" -eq '2' || return "${rc}"
}

# Gateway's certificate
if ! test -f "/eaas/certificates/server.crt"; then
	__acmesh --dns "${ACMESH_DNS_API}" --deploy-hook nghttpx --issue -d "${EAAS_DOMAIN}"
	__acmesh --dns "${ACMESH_DNS_API}" --deploy-hook nghttpx --deploy -d "${EAAS_DOMAIN}"
fi

domain="*.${EAAS_DOMAIN}"
certfile="${acmeshdir}/${domain}/fullchain.cer"

# Certificate for all emucomps
if ! test -f "${certfile}" ; then
	# Uncomment if you want Let's Encrypt to generate test certificates.
	# testmode="--test"
	testmode=''

	# Note: `--days 30` will renew the certificate every 30 days.
	__acmesh ${testmode} --dns "${ACMESH_DNS_API}" --days 30 --issue -d "${domain}"
fi
