#!/bin/sh

. /home/bwfla/.bwFLA/dns-env || exit

export DEPLOY_NGHTTPX_RELOAD="/libexec/update-nghttpx"

if ! test -f "/eaas/certificates/server.crt"; then
	export LE_CONFIG_HOME="/home/bwfla/server-data/acme.sh"
	/usr/local/acme.sh/acme.sh --dns "${ACMESH_DNS_API:?}" --deploy-hook nghttpx --issue -d "${EAAS_DOMAIN:?}"
	/usr/local/acme.sh/acme.sh --dns "${ACMESH_DNS_API}" --deploy-hook nghttpx --deploy -d "${EAAS_DOMAIN}"
fi
